# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [31]:
# Completar o exercício aqui
import numpy as np

#Criar um array de elementos (de 10 a 100)
array_100 = np.arange(10,101)
print("-----Criar um array de elementos de 10 a 100-----")
print(array_100)
print(" ")

#Inverter o array
array_invertido = np.flip(array_100)
print("-----Inverter o array-----")
print(array_invertido)
print(" ")

#Criar um array 3x3 com valores de 0 a 8
array_9_elementos = np.arange(9)

array_3x3 = np.reshape(array_9_elementos,[3,3])
print("-----Criar um array 3x3 com valores de 0 a 8-----")
print(array_3x3)
print(" ")

#Criar um array identidade de 6x6
array_identity = np.identity(6)
print("-----Criar um array identidade de 6x6------")
print(array_identity)
print(" ")

#Criar um array com valores aleatórios com o formato 3x3x3
array_aleatorio_3x3x3 = np.random.randint(27,size=(3,3,3))
print("-----Criar um array com valores aleatórios com o formato 3x3x3-----")
print(array_aleatorio_3x3x3)
print(" ")

# Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)
array_1 = np.array([[2,4],[6,8]])
array_2 = np.array([[3,5],[7,9]])
print("-----Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)-----")
print(array_1,array_2)
print(np.array_equal(array_1,array_2))
array_1 = np.array([[2,4],[6,8]])
array_2 = np.array([[2,4],[6,8]])
print(np.equal(array_1,array_2))


-----Criar um array de elementos de 10 a 100-----
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
 
-----Inverter o array-----
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
 
-----Criar um array 3x3 com valores de 0 a 8-----
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
-----Criar um array identidade de 6x6------
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [33]:
# Completar o exercício aqui
import numpy as np

"""dolares = np.linspace(1,1000,100).astype(int)

    quando uso o linspace iniciando pelo numero 1 , a funcao round() mostra um valor diferente quando colocar mais de uma casa decimal
"""
print("-----Criando array com 100 elementos aleatórios-----")
dolares = np.linspace(2,1000,100).astype(int)
print(dolares)
#conversão dolares para euro
converter = dolares*0.874413
euro = np.round(converter, decimals=2) #QUando coloco para mais de uma casa decimal, não me retorna o valor numero normal(ex.: 8.7000e-01)
print(euro.round(2))


-----Criando array com 100 elementos aleatórios-----
[   2   12   22   32   42   52   62   72   82   92  102  112  122  133
  143  153  163  173  183  193  203  213  223  233  243  254  264  274
  284  294  304  314  324  334  344  354  364  374  385  395  405  415
  425  435  445  455  465  475  485  495  506  516  526  536  546  556
  566  576  586  596  606  616  627  637  647  657  667  677  687  697
  707  717  727  737  747  758  768  778  788  798  808  818  828  838
  848  858  868  879  889  899  909  919  929  939  949  959  969  979
  989 1000]
[  1.75  10.49  19.24  27.98  36.73  45.47  54.21  62.96  71.7   80.45
  89.19  97.93 106.68 116.3  125.04 133.79 142.53 151.27 160.02 168.76
 177.51 186.25 194.99 203.74 212.48 222.1  230.85 239.59 248.33 257.08
 265.82 274.57 283.31 292.05 300.8  309.54 318.29 327.03 336.65 345.39
 354.14 362.88 371.63 380.37 389.11 397.86 406.6  415.35 424.09 432.83
 442.45 451.2  459.94 468.69 477.43 486.17 494.92 503.66 512.41 521.15
 529.89 538.

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [29]:
# Completar o exercício aqui
import pandas as pd

#Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
df_titulos = pd.read_csv("05_05_imdb_titulos.csv")
print("----- Os 5 primeiros registros de titulos-----")
print(df_titulos.head(5))
print(" ")


#Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
df_elenco = pd.read_csv("05_05_imdb_elenco.csv")
print("----- Os 5 primeiros registros de elenco-----")
print(df_elenco.head(5))
print(" ")


#Mostrar o número de registos do dataframe de títulos.
print(f'O numero de registros do arquivo csv titulos: {df_titulos.index.stop}')


#Mostrar o número de registos do dataframe de elenco.
print(f'O numero de registros do arquivo csv elenco: {df_elenco.index.stop}')


#Mostrar os 5 titulos mais antigos.
print(" ")
print("----- Os 5 Ultimos registros de titulos mais antigos-----")
titulos_antigo = df_titulos.sort_values("year")
print(titulos_antigo.head(5))


#Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
print(" ")
filme_dracula = df_titulos[df_titulos["title"].str.contains("Dracula")]
print("-----Título que contem a palavra “Drácula”-----")
print(filme_dracula)
print(f'Temos um total de {len(filme_dracula)} filmes com o nome Dracula')


#Mostrar os 10 títulos mais comuns (que mais se repetem).
print(" ")
print("-----Mostrar os 10 títulos mais comuns-----")
titulos_repetidos = df_titulos.groupby("title").size().sort_values(ascending=False)
print(titulos_repetidos.head(10))


#Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
print(" ")
filme_romeoAndJuliet = df_titulos[df_titulos["title"] == "Romeo and Juliet"]
print("-----Primeiro filme chamado “Romeo and Juliet”-----")
print(filme_romeoAndJuliet["year"].sort_values(ascending=True).head(1))


#Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
print(" ")
filmes_exorcist = df_titulos[df_titulos["title"].str.contains("Exorcist")]
print("----- filmes que contenham a palavra “Exorcist”-----")
print(filmes_exorcist.sort_values("year"))


#Mostrar quantos filmes foram feitas no ano 1950.
print(" ")
filmes_1950 = df_titulos[df_titulos["year"] == 1950]
print("-----Mostrar quantos filmes foram feitas no ano 1950-----")
print(len(filmes_1950))


#Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
print(" ")
filmes_1950_1959 = df_titulos[(df_titulos["year"] >= 1950) & (df_titulos["year"] <= 1959) ]
print("-----Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive)-----")
print(filmes_1950_1959)
print(f'Foram feitos {len(filmes_1950_1959)} filmes entre 1950 e 1959')


#Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a
#informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
print(" ")
godfather = df_elenco[df_elenco["title"].str.contains("The Godfather")]
character = godfather.groupby("name").size().sort_values(ascending=False)
print("-----Papeis da pelicula 'Godfather'-----")
print(character)


#Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958
print(" ")
print("-----elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958-----")
elenco_dracula = df_elenco[(df_elenco["title"]==("Dracula")) & ((df_elenco["year"] == 1958))]
print(elenco_dracula.sort_values("n"))


#Mostrar quantos papéis teve “Bruce Wayne” como protagonista
#(Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
print(" ")
print("-----Quantos papéis teve “Bruce Wayne” como protagonista-----")
papel_bruce_wayne = df_elenco[df_elenco["character"].str.contains("Bruce Wayne")]
print(papel_bruce_wayne.count())


#Mostrar quantos papéis fez “Robert de Niro” na sua carreira
print(" ")
print("-----Mostrar quantos papéis fez “Robert de Niro” na sua carreira-----")
papeis_robert = df_elenco[df_elenco["name"].str.contains("Robert De Niro")]
print(len(papeis_robert))


#Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na
#década dos 60’s, ordenado por ano de forma descendente.
print(" ")
print("-----Listagem de papéis como protagonista que teve o ator “Charlton Heston” ordenado por ano de forma descendente.-----")
papeis_charlton = df_elenco[(df_elenco["name"].str.contains("Charlton Heston")) & (df_elenco["n"]==1) & (df_elenco["year"] >= 1960) & (df_elenco["year"] <= 1969) ]
print(papeis_charlton.sort_values("year"))


#Mostrar quantos papéis para atores teve na década 50’s.
print(" ")
print("-----Mostrar quantos papéis para atores teve na década 50’s.-----")
papeis_atores = df_elenco[(df_elenco["type"].str.contains("actor")) & (df_elenco["year"] >= 1950) & (df_elenco["year"] <=1959)]
print(len(papeis_atores))


#Mostrar quantos papéis para atrizes teve na década 50’s.
print(" ")
print("-----Mostrar quantos papéis para atores teve na década 50’s.-----")
papeis_atrizes = df_elenco[(df_elenco["type"].str.contains("actress")) & (df_elenco["year"] >= 1950) & (df_elenco["year"] <=1959)]
print(len(papeis_atrizes))

----- Os 5 primeiros registros de titulos-----
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989
 
----- Os 5 primeiros registros de elenco-----
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN
 
O numero de registros do arquivo csv titulos: 230407
O numero de registros do arquivo csv elenco: 3564650
 
----- Os 5 Ultimos registros de titulos mais 

153998
 
-----Mostrar quantos papéis para atores teve na década 50’s.-----
56004
